#!/usr/bin/env python3
"""Generate daily vision documentation from story-tree database."""

import sqlite3
import subprocess
from datetime import datetime, timezone
from pathlib import Path

# Paths
REPO_ROOT = Path(__file__).parent.parent.parent
DB_PATH = REPO_ROOT / ".claude/data/story-tree.db"
TREE_SCRIPT = REPO_ROOT / ".claude/skills/story-tree/scripts/tree-view.py"
OUTPUT_DIR = REPO_ROOT / ".claude/data/github_action_results"

def main():
    # Get tree visualization
    tree_output = subprocess.run(
        ["python", str(TREE_SCRIPT), "--show-capacity"],
        capture_output=True,
        text=True
    ).stdout

    # Connect to database
    conn = sqlite3.connect(str(DB_PATH))
    cursor = conn.cursor()

    # Get timestamp
    now = datetime.now(timezone.utc)
    timestamp = now.strftime('%Y-%m-%d %H:%M:%S UTC')
    date_str = now.strftime('%Y-%m-%d')

    # Get overall stats
    cursor.execute('SELECT COUNT(*) FROM story_nodes')
    total_stories = cursor.fetchone()[0]

    cursor.execute("""
        SELECT stage, COUNT(*)
        FROM story_nodes
        WHERE disposition IS NULL AND hold_reason IS NULL
        GROUP BY stage
        ORDER BY
            CASE stage
                WHEN 'concept' THEN 1
                WHEN 'approved' THEN 2
                WHEN 'planned' THEN 3
                WHEN 'active' THEN 4
                WHEN 'reviewing' THEN 5
                WHEN 'verifying' THEN 6
                WHEN 'implemented' THEN 7
                WHEN 'ready' THEN 8
                WHEN 'polish' THEN 9
                WHEN 'released' THEN 10
            END
    """)
    active_by_stage = cursor.fetchall()

    cursor.execute("""
        SELECT disposition, COUNT(*)
        FROM story_nodes
        WHERE disposition IS NOT NULL
        GROUP BY disposition
    """)
    disposed = cursor.fetchall()

    cursor.execute("""
        SELECT hold_reason, COUNT(*)
        FROM story_nodes
        WHERE hold_reason IS NOT NULL
        GROUP BY hold_reason
    """)
    held = cursor.fetchall()

    conn.close()

    # Build the content
    content = f"""# SyncoPaid Story Tree Visualization

> Auto-generated visualization of story tree database

## Run Details

| Field | Value |
|-------|-------|
| Generated | {timestamp} |
| Total Stories | {total_stories} |

## Active Stories by Stage

| Stage | Count |
|-------|-------|
"""

    for stage, count in active_by_stage:
        content += f"| {stage} | {count} |\n"

    if held:
        content += "\n## Held Stories\n\n| Hold Reason | Count |\n|-------------|-------|\n"
        for reason, count in held:
            content += f"| {reason} | {count} |\n"

    if disposed:
        content += "\n## Disposed Stories\n\n| Disposition | Count |\n|-------------|-------|\n"
        for disp, count in disposed:
            content += f"| {disp} | {count} |\n"

    content += f"""
## Tree Structure

```
{tree_output}```

---
*Generated by daily visualization workflow*
"""

    # Write output
    output_file = OUTPUT_DIR / f"{date_str}-tree-visualization.md"
    output_file.write_text(content)
    print(f"Generated: {output_file}")

if __name__ == "__main__":
    main()
